name: MineAWSIPs

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: aws-ips
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Pull the AWS IPs
        run: |-
          nslookup www.aws.com > ./temp/raw_aws.txt
          grep "Address:" < ./temp/raw_aws.txt > ./temp/addresses.txt
          grep -v "#53" < ./temp/addresses.txt > ./ipsonly.txt
          awk '{print $2}' < ./temp/ipsonly.txt > ./temp/awsips.txt
      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
