name: MineDshieldTop20

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '3 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: dshield
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Pull the Block List
        run: |-
          curl "https://feeds.dshield.org/block.txt" -o ./temp/block.txt || true
          ./scripts/dshield-ip-list.py ./temp/block.txt > dshieldbl.txt
      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
